class newTask{

    constructor(){

        this.task = {id: "", title: "", complete: "false"};
    }
    
}

function toDoList(){
    var list = [];
    
    this.addTask = function (title){ //post
        let id = Math.floor(Math.random() * 100000);
        var h = new newTask().task;
        h.id = id;
        h.title = title;
        h.complete = "false"
        list.push(h);
        return `Task ${id} added succesfully!`;
        
    }


    this.updateTask = function (id, title){//put
        var taskNumber = 0;
        var oldTitle = 0;

        list.forEach((item)=>{
            if (item.id == id){
                taskNumber = item.id;
                oldTitle = item.title;
                item.title = title;
            }
                
        })

        return `Task ${taskNumber} title: '${oldTitle}' updated to '${title}' succesfully!`;

    }

    this.getTask = function (id){ //get
        var message = "";

        list.forEach((item)=>{
            if (item.id == id){

                if (item.complete == "false")
                    message = `Task with id: '${item.id}' and titled '${item.title}' still incomplete`;
                else
                    message = `Task with id: '${item.id}' and titled '${item.title}' completed`;     
            }
        })

        if (message != "")
            return message;
        else
            return "Task not found";
    }

    this.deleteTask = function (id){ //delete

        for (var i = 0; i < list.length; i++){
            if (list[i].id == id)
                list.splice(i,1);
        }
        
        return `Task ${id} deleted succesfully!`;
    }

    this.completeATask = function(id){ //complete a task / change from false to true
        list.forEach((item)=>{
            if(item.id == id)
                item.complete = "true";
        });
        return `Task with ${id} completed succesfully!`;
    }

    this.printTasks = function (){
        console.log(list);
    }
}

const h = new toDoList();
console.log(h.addTask("Complete job tables"));
console.log(h.addTask("Breakfast"));
console.log(h.addTask("Play football"));
console.log(h.addTask("Swim at the beach"));
console.log(h.printTasks());
console.log(h.updateTask(2, "Jump in bungeejump"));//these id numbers were used in another scenario where the id was generated by the author;
console.log(h.printTasks());
console.log(h.completeATask(3));
console.log(h.printTasks());
console.log(h.deleteTask(2));
console.log(h.printTasks()); 
